### ISSUE TITLE
Setup Testing and Continuous Integration

### ISSUE THREAD

**Issue by estebanespinoza24** [garfield-hates-monday/ruby-on-rails-chess#1]
-Pick a testing framework: Rspec or Minitest.
-Decide on using Factory Girl, Capybara, etc.
-Write a single passing test ( can be just assert true ) to verify the testing framework is working properly.
-Pick a CI service. Our options can be: TravisCI, CodeShip, CircleCI, or.... have the team pick one.

**Comment by gregory-eglen** [comment]
Branch merged.
